// AUTO-GENERATED by scripts/gen-types-local.sh from supabase/migrations/*.sql.
// Do NOT edit by hand. Regenerate locally (never against hosted Supabase).

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  public: {
    Tables: {
      app_contracts: {
        Row: {
          app_id: string
          contract_id: string
          created_at: string
          relationship_type: string | null
          tenant_id: string
        }
        Insert: {
          app_id: string
          contract_id: string
          created_at?: string
          relationship_type?: string | null
          tenant_id: string
        }
        Update: {
          app_id?: string
          contract_id?: string
          created_at?: string
          relationship_type?: string | null
          tenant_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "app_contracts_app_id_fkey"
            columns: ["app_id"]
            isOneToOne: false
            referencedRelation: "apps"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "app_contracts_app_same_tenant"
            columns: ["app_id", "tenant_id"]
            isOneToOne: false
            referencedRelation: "apps"
            referencedColumns: ["id", "tenant_id"]
          },
          {
            foreignKeyName: "app_contracts_contract_id_fkey"
            columns: ["contract_id"]
            isOneToOne: false
            referencedRelation: "contracts"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "app_contracts_contract_same_tenant"
            columns: ["contract_id", "tenant_id"]
            isOneToOne: false
            referencedRelation: "contracts"
            referencedColumns: ["id", "tenant_id"]
          },
          {
            foreignKeyName: "app_contracts_tenant_id_fkey"
            columns: ["tenant_id"]
            isOneToOne: false
            referencedRelation: "tenants"
            referencedColumns: ["id"]
          },
        ]
      }
      app_user_identity_matches: {
        Row: {
          app_user_id: string
          confidence: number | null
          created_at: string
          id: string
          match_method: string
          person_id: string
          reviewed_at: string | null
          reviewed_by: string | null
          tenant_id: string
        }
        Insert: {
          app_user_id: string
          confidence?: number | null
          created_at?: string
          id?: string
          match_method: string
          person_id: string
          reviewed_at?: string | null
          reviewed_by?: string | null
          tenant_id: string
        }
        Update: {
          app_user_id?: string
          confidence?: number | null
          created_at?: string
          id?: string
          match_method?: string
          person_id?: string
          reviewed_at?: string | null
          reviewed_by?: string | null
          tenant_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "app_user_identity_matches_app_user_id_fkey"
            columns: ["app_user_id"]
            isOneToOne: false
            referencedRelation: "app_users"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "app_user_identity_matches_person_id_fkey"
            columns: ["person_id"]
            isOneToOne: false
            referencedRelation: "people"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "app_user_identity_matches_reviewed_by_fkey"
            columns: ["reviewed_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "app_user_identity_matches_tenant_id_fkey"
            columns: ["tenant_id"]
            isOneToOne: false
            referencedRelation: "tenants"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "auim_app_user_same_tenant"
            columns: ["app_user_id", "tenant_id"]
            isOneToOne: false
            referencedRelation: "app_users"
            referencedColumns: ["id", "tenant_id"]
          },
          {
            foreignKeyName: "auim_person_same_tenant"
            columns: ["person_id", "tenant_id"]
            isOneToOne: false
            referencedRelation: "people"
            referencedColumns: ["id", "tenant_id"]
          },
        ]
      }
      app_users: {
        Row: {
          app_id: string
          created_at: string
          display_name: string | null
          email: string | null
          external_user_id: string | null
          id: string
          last_active_at: string | null
          license_type: string | null
          raw_payload: Json | null
          source: string | null
          status: string | null
          tenant_id: string
          updated_at: string
        }
        Insert: {
          app_id: string
          created_at?: string
          display_name?: string | null
          email?: string | null
          external_user_id?: string | null
          id?: string
          last_active_at?: string | null
          license_type?: string | null
          raw_payload?: Json | null
          source?: string | null
          status?: string | null
          tenant_id: string
          updated_at?: string
        }
        Update: {
          app_id?: string
          created_at?: string
          display_name?: string | null
          email?: string | null
          external_user_id?: string | null
          id?: string
          last_active_at?: string | null
          license_type?: string | null
          raw_payload?: Json | null
          source?: string | null
          status?: string | null
          tenant_id?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "app_users_app_id_fkey"
            columns: ["app_id"]
            isOneToOne: false
            referencedRelation: "apps"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "app_users_app_same_tenant"
            columns: ["app_id", "tenant_id"]
            isOneToOne: false
            referencedRelation: "apps"
            referencedColumns: ["id", "tenant_id"]
          },
          {
            foreignKeyName: "app_users_tenant_id_fkey"
            columns: ["tenant_id"]
            isOneToOne: false
            referencedRelation: "tenants"
            referencedColumns: ["id"]
          },
        ]
      }
      apps: {
        Row: {
          business_owner_user_id: string | null
          category: string | null
          created_at: string
          id: string
          name: string
          notes: string | null
          paying_org_id: string | null
          procurement_owner_org_id: string | null
          responsible_org_id: string | null
          source_of_truth_type: string | null
          status: string
          technical_owner_user_id: string | null
          tenant_id: string
          updated_at: string
          vendor_name: string | null
        }
        Insert: {
          business_owner_user_id?: string | null
          category?: string | null
          created_at?: string
          id?: string
          name: string
          notes?: string | null
          paying_org_id?: string | null
          procurement_owner_org_id?: string | null
          responsible_org_id?: string | null
          source_of_truth_type?: string | null
          status?: string
          technical_owner_user_id?: string | null
          tenant_id: string
          updated_at?: string
          vendor_name?: string | null
        }
        Update: {
          business_owner_user_id?: string | null
          category?: string | null
          created_at?: string
          id?: string
          name?: string
          notes?: string | null
          paying_org_id?: string | null
          procurement_owner_org_id?: string | null
          responsible_org_id?: string | null
          source_of_truth_type?: string | null
          status?: string
          technical_owner_user_id?: string | null
          tenant_id?: string
          updated_at?: string
          vendor_name?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "apps_business_owner_user_id_fkey"
            columns: ["business_owner_user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "apps_paying_org_id_fkey"
            columns: ["paying_org_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "apps_procurement_owner_org_id_fkey"
            columns: ["procurement_owner_org_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "apps_responsible_org_id_fkey"
            columns: ["responsible_org_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "apps_technical_owner_user_id_fkey"
            columns: ["technical_owner_user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "apps_tenant_id_fkey"
            columns: ["tenant_id"]
            isOneToOne: false
            referencedRelation: "tenants"
            referencedColumns: ["id"]
          },
        ]
      }
      audit_logs: {
        Row: {
          action: string
          actor_user_id: string | null
          after_json: Json | null
          before_json: Json | null
          created_at: string
          id: string
          ip_address: unknown
          resource_id: string | null
          resource_type: string
          tenant_id: string
          user_agent: string | null
        }
        Insert: {
          action: string
          actor_user_id?: string | null
          after_json?: Json | null
          before_json?: Json | null
          created_at?: string
          id?: string
          ip_address?: unknown
          resource_id?: string | null
          resource_type: string
          tenant_id: string
          user_agent?: string | null
        }
        Update: {
          action?: string
          actor_user_id?: string | null
          after_json?: Json | null
          before_json?: Json | null
          created_at?: string
          id?: string
          ip_address?: unknown
          resource_id?: string | null
          resource_type?: string
          tenant_id?: string
          user_agent?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "audit_logs_actor_user_id_fkey"
            columns: ["actor_user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "audit_logs_tenant_id_fkey"
            columns: ["tenant_id"]
            isOneToOne: false
            referencedRelation: "tenants"
            referencedColumns: ["id"]
          },
        ]
      }
      contracts: {
        Row: {
          billing_frequency: string | null
          contract_name: string
          created_at: string
          currency: string | null
          end_date: string | null
          id: string
          notice_deadline: string | null
          owner_user_id: string | null
          paying_org_id: string | null
          procurement_org_id: string | null
          renewal_date: string | null
          renewal_responsibility: string | null
          start_date: string | null
          status: string
          tenant_id: string
          total_cost: number | null
          updated_at: string
          vendor_name: string | null
        }
        Insert: {
          billing_frequency?: string | null
          contract_name: string
          created_at?: string
          currency?: string | null
          end_date?: string | null
          id?: string
          notice_deadline?: string | null
          owner_user_id?: string | null
          paying_org_id?: string | null
          procurement_org_id?: string | null
          renewal_date?: string | null
          renewal_responsibility?: string | null
          start_date?: string | null
          status?: string
          tenant_id: string
          total_cost?: number | null
          updated_at?: string
          vendor_name?: string | null
        }
        Update: {
          billing_frequency?: string | null
          contract_name?: string
          created_at?: string
          currency?: string | null
          end_date?: string | null
          id?: string
          notice_deadline?: string | null
          owner_user_id?: string | null
          paying_org_id?: string | null
          procurement_org_id?: string | null
          renewal_date?: string | null
          renewal_responsibility?: string | null
          start_date?: string | null
          status?: string
          tenant_id?: string
          total_cost?: number | null
          updated_at?: string
          vendor_name?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "contracts_owner_user_id_fkey"
            columns: ["owner_user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "contracts_paying_org_id_fkey"
            columns: ["paying_org_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "contracts_procurement_org_id_fkey"
            columns: ["procurement_org_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "contracts_tenant_id_fkey"
            columns: ["tenant_id"]
            isOneToOne: false
            referencedRelation: "tenants"
            referencedColumns: ["id"]
          },
        ]
      }
      files: {
        Row: {
          created_at: string
          document_type: string | null
          file_type: string | null
          id: string
          original_filename: string
          processing_status: string
          storage_path: string
          tenant_id: string
          uploaded_by: string | null
        }
        Insert: {
          created_at?: string
          document_type?: string | null
          file_type?: string | null
          id?: string
          original_filename: string
          processing_status?: string
          storage_path: string
          tenant_id: string
          uploaded_by?: string | null
        }
        Update: {
          created_at?: string
          document_type?: string | null
          file_type?: string | null
          id?: string
          original_filename?: string
          processing_status?: string
          storage_path?: string
          tenant_id?: string
          uploaded_by?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "files_tenant_id_fkey"
            columns: ["tenant_id"]
            isOneToOne: false
            referencedRelation: "tenants"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "files_uploaded_by_fkey"
            columns: ["uploaded_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      identity_accounts: {
        Row: {
          created_at: string
          email: string
          external_id: string | null
          id: string
          person_id: string | null
          provider: string
          raw_payload: Json | null
          status: string | null
          tenant_id: string
          updated_at: string
        }
        Insert: {
          created_at?: string
          email: string
          external_id?: string | null
          id?: string
          person_id?: string | null
          provider: string
          raw_payload?: Json | null
          status?: string | null
          tenant_id: string
          updated_at?: string
        }
        Update: {
          created_at?: string
          email?: string
          external_id?: string | null
          id?: string
          person_id?: string | null
          provider?: string
          raw_payload?: Json | null
          status?: string | null
          tenant_id?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "identity_accounts_person_id_fkey"
            columns: ["person_id"]
            isOneToOne: false
            referencedRelation: "people"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "identity_accounts_person_same_tenant"
            columns: ["person_id", "tenant_id"]
            isOneToOne: false
            referencedRelation: "people"
            referencedColumns: ["id", "tenant_id"]
          },
          {
            foreignKeyName: "identity_accounts_tenant_id_fkey"
            columns: ["tenant_id"]
            isOneToOne: false
            referencedRelation: "tenants"
            referencedColumns: ["id"]
          },
        ]
      }
      invoices: {
        Row: {
          amount: number | null
          app_id: string | null
          contract_id: string | null
          created_at: string
          currency: string | null
          file_id: string | null
          id: string
          invoice_date: string | null
          invoice_number: string | null
          tenant_id: string
          vendor_name: string | null
        }
        Insert: {
          amount?: number | null
          app_id?: string | null
          contract_id?: string | null
          created_at?: string
          currency?: string | null
          file_id?: string | null
          id?: string
          invoice_date?: string | null
          invoice_number?: string | null
          tenant_id: string
          vendor_name?: string | null
        }
        Update: {
          amount?: number | null
          app_id?: string | null
          contract_id?: string | null
          created_at?: string
          currency?: string | null
          file_id?: string | null
          id?: string
          invoice_date?: string | null
          invoice_number?: string | null
          tenant_id?: string
          vendor_name?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "invoices_app_id_fkey"
            columns: ["app_id"]
            isOneToOne: false
            referencedRelation: "apps"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "invoices_app_same_tenant"
            columns: ["app_id", "tenant_id"]
            isOneToOne: false
            referencedRelation: "apps"
            referencedColumns: ["id", "tenant_id"]
          },
          {
            foreignKeyName: "invoices_contract_id_fkey"
            columns: ["contract_id"]
            isOneToOne: false
            referencedRelation: "contracts"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "invoices_contract_same_tenant"
            columns: ["contract_id", "tenant_id"]
            isOneToOne: false
            referencedRelation: "contracts"
            referencedColumns: ["id", "tenant_id"]
          },
          {
            foreignKeyName: "invoices_file_id_fkey"
            columns: ["file_id"]
            isOneToOne: false
            referencedRelation: "files"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "invoices_file_same_tenant"
            columns: ["file_id", "tenant_id"]
            isOneToOne: false
            referencedRelation: "files"
            referencedColumns: ["id", "tenant_id"]
          },
          {
            foreignKeyName: "invoices_tenant_id_fkey"
            columns: ["tenant_id"]
            isOneToOne: false
            referencedRelation: "tenants"
            referencedColumns: ["id"]
          },
        ]
      }
      license_evaluations: {
        Row: {
          app_id: string
          app_user_id: string
          evaluated_at: string
          explanation: string | null
          id: string
          is_billable: boolean
          license_rule_id: string | null
          license_type: string | null
          tenant_id: string
        }
        Insert: {
          app_id: string
          app_user_id: string
          evaluated_at?: string
          explanation?: string | null
          id?: string
          is_billable?: boolean
          license_rule_id?: string | null
          license_type?: string | null
          tenant_id: string
        }
        Update: {
          app_id?: string
          app_user_id?: string
          evaluated_at?: string
          explanation?: string | null
          id?: string
          is_billable?: boolean
          license_rule_id?: string | null
          license_type?: string | null
          tenant_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "license_evaluations_app_id_fkey"
            columns: ["app_id"]
            isOneToOne: false
            referencedRelation: "apps"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "license_evaluations_app_same_tenant"
            columns: ["app_id", "tenant_id"]
            isOneToOne: false
            referencedRelation: "apps"
            referencedColumns: ["id", "tenant_id"]
          },
          {
            foreignKeyName: "license_evaluations_app_user_id_fkey"
            columns: ["app_user_id"]
            isOneToOne: false
            referencedRelation: "app_users"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "license_evaluations_app_user_same_tenant"
            columns: ["app_user_id", "tenant_id"]
            isOneToOne: false
            referencedRelation: "app_users"
            referencedColumns: ["id", "tenant_id"]
          },
          {
            foreignKeyName: "license_evaluations_license_rule_id_fkey"
            columns: ["license_rule_id"]
            isOneToOne: false
            referencedRelation: "license_rules"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "license_evaluations_rule_same_tenant"
            columns: ["license_rule_id", "tenant_id"]
            isOneToOne: false
            referencedRelation: "license_rules"
            referencedColumns: ["id", "tenant_id"]
          },
          {
            foreignKeyName: "license_evaluations_tenant_id_fkey"
            columns: ["tenant_id"]
            isOneToOne: false
            referencedRelation: "tenants"
            referencedColumns: ["id"]
          },
        ]
      }
      license_rules: {
        Row: {
          active: boolean
          app_id: string
          created_at: string
          expression_json: Json
          id: string
          license_type: string | null
          name: string
          tenant_id: string
          updated_at: string
        }
        Insert: {
          active?: boolean
          app_id: string
          created_at?: string
          expression_json?: Json
          id?: string
          license_type?: string | null
          name: string
          tenant_id: string
          updated_at?: string
        }
        Update: {
          active?: boolean
          app_id?: string
          created_at?: string
          expression_json?: Json
          id?: string
          license_type?: string | null
          name?: string
          tenant_id?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "license_rules_app_id_fkey"
            columns: ["app_id"]
            isOneToOne: false
            referencedRelation: "apps"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "license_rules_app_same_tenant"
            columns: ["app_id", "tenant_id"]
            isOneToOne: false
            referencedRelation: "apps"
            referencedColumns: ["id", "tenant_id"]
          },
          {
            foreignKeyName: "license_rules_tenant_id_fkey"
            columns: ["tenant_id"]
            isOneToOne: false
            referencedRelation: "tenants"
            referencedColumns: ["id"]
          },
        ]
      }
      organization_memberships: {
        Row: {
          created_at: string
          id: string
          organization_id: string
          role: string
          user_id: string
        }
        Insert: {
          created_at?: string
          id?: string
          organization_id: string
          role: string
          user_id: string
        }
        Update: {
          created_at?: string
          id?: string
          organization_id?: string
          role?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "organization_memberships_organization_id_fkey"
            columns: ["organization_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "organization_memberships_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      organizations: {
        Row: {
          created_at: string
          id: string
          name: string
          parent_org_id: string | null
          tenant_id: string
          type: string
          updated_at: string
        }
        Insert: {
          created_at?: string
          id?: string
          name: string
          parent_org_id?: string | null
          tenant_id: string
          type?: string
          updated_at?: string
        }
        Update: {
          created_at?: string
          id?: string
          name?: string
          parent_org_id?: string | null
          tenant_id?: string
          type?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "organizations_parent_org_id_fkey"
            columns: ["parent_org_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "organizations_parent_same_tenant"
            columns: ["parent_org_id", "tenant_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id", "tenant_id"]
          },
          {
            foreignKeyName: "organizations_tenant_id_fkey"
            columns: ["tenant_id"]
            isOneToOne: false
            referencedRelation: "tenants"
            referencedColumns: ["id"]
          },
        ]
      }
      people: {
        Row: {
          created_at: string
          department: string | null
          employee_status: string | null
          full_name: string | null
          id: string
          manager_email: string | null
          primary_email: string
          raw_payload: Json | null
          source: string | null
          tenant_id: string
          title: string | null
          updated_at: string
        }
        Insert: {
          created_at?: string
          department?: string | null
          employee_status?: string | null
          full_name?: string | null
          id?: string
          manager_email?: string | null
          primary_email: string
          raw_payload?: Json | null
          source?: string | null
          tenant_id: string
          title?: string | null
          updated_at?: string
        }
        Update: {
          created_at?: string
          department?: string | null
          employee_status?: string | null
          full_name?: string | null
          id?: string
          manager_email?: string | null
          primary_email?: string
          raw_payload?: Json | null
          source?: string | null
          tenant_id?: string
          title?: string | null
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "people_tenant_id_fkey"
            columns: ["tenant_id"]
            isOneToOne: false
            referencedRelation: "tenants"
            referencedColumns: ["id"]
          },
        ]
      }
      profiles: {
        Row: {
          created_at: string
          email: string
          full_name: string | null
          id: string
          updated_at: string
        }
        Insert: {
          created_at?: string
          email: string
          full_name?: string | null
          id: string
          updated_at?: string
        }
        Update: {
          created_at?: string
          email?: string
          full_name?: string | null
          id?: string
          updated_at?: string
        }
        Relationships: []
      }
      tenant_memberships: {
        Row: {
          created_at: string
          id: string
          role: string
          status: string
          tenant_id: string
          user_id: string
        }
        Insert: {
          created_at?: string
          id?: string
          role: string
          status?: string
          tenant_id: string
          user_id: string
        }
        Update: {
          created_at?: string
          id?: string
          role?: string
          status?: string
          tenant_id?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "tenant_memberships_tenant_id_fkey"
            columns: ["tenant_id"]
            isOneToOne: false
            referencedRelation: "tenants"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "tenant_memberships_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      tenants: {
        Row: {
          created_at: string
          id: string
          name: string
          slug: string
          status: string
          updated_at: string
        }
        Insert: {
          created_at?: string
          id?: string
          name: string
          slug: string
          status?: string
          updated_at?: string
        }
        Update: {
          created_at?: string
          id?: string
          name?: string
          slug?: string
          status?: string
          updated_at?: string
        }
        Relationships: []
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      dearmor: { Args: { "": string }; Returns: string }
      gen_random_uuid: { Args: never; Returns: string }
      gen_salt: { Args: { "": string }; Returns: string }
      has_org_role: {
        Args: { allowed_roles: string[]; target_org_id: string }
        Returns: boolean
      }
      has_org_role_in_tenant: {
        Args: {
          allowed_roles: string[]
          target_org_id: string
          target_tenant_id: string
        }
        Returns: boolean
      }
      has_tenant_role: {
        Args: { allowed_roles: string[]; target_tenant_id: string }
        Returns: boolean
      }
      is_org_member: { Args: { target_org_id: string }; Returns: boolean }
      is_tenant_member: { Args: { target_tenant_id: string }; Returns: boolean }
      is_tenant_participant: {
        Args: { target_tenant_id: string }
        Returns: boolean
      }
      pgp_armor_headers: {
        Args: { "": string }
        Returns: Record<string, unknown>[]
      }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {},
  },
} as const

