// O2A — the V3 port of the O1C identity derivation must produce BYTE-IDENTICAL fingerprints to the connector-runner's.
//
// The two repositories share no package, so the algorithm exists in both. These KNOWN-ANSWER VECTORS were produced by the
// connector-runner implementation and are asserted in BOTH repositories. If either drifts, that repository's test fails — the same
// mechanism the O1B contract hash uses.
//
// A fingerprint mismatch would be silent and severe: V3 would persist one organization identity while the runner derived another,
// so a legitimate reconnect would read as `different_organization` and be rejected.

import { describe, it, expect } from "vitest";
import {
  canonicalizeOktaOrgHost, deriveOktaOrganizationIdentity, OKTA_APEX_DOMAINS, OKTA_IDENTITY_VERSION,
} from "./okta-org-identity";

// Generated by idcaddie-connector-runner @ 3b671ef, src/connector-sync/okta-organization-identity.ts.
const VECTORS = [
  {
    host: "acme.okta.com",
    clientId: "0oa15fcokefFqDREa698",
    org: "a06d12944d95f3bc8a699d0994e48f606720d297515469dad2bd217572955252",
    app: "a78cd39f3c967d74e27bf9e929e63f07b515bf6e9412da9ec9b6f06bf0c7c73c",
  },
  {
    host: "acme.oktapreview.com",
    clientId: "0oaSECONDapp00002",
    org: "27d8e2cc9f203a7f084e2fac911efdde71e218429488cdcd2ac04d37d9f25cae",
    app: "10acfa2b7626869ff7bc6af63876d5f4ccab2b08e58d0972cd816ee2d3f3f01f",
  },
] as const;

describe("cross-repository fingerprint agreement", () => {
  it.each(VECTORS)("matches the runner for $host", ({ host, clientId, org, app }) => {
    const r = deriveOktaOrganizationIdentity({ orgHost: host, clientId });
    expect(r.ok).toBe(true);
    if (!r.ok) return;
    expect(r.identity.organizationFingerprint).toBe(org);
    expect(r.identity.serviceAppFingerprint).toBe(app);
  });

  it("derives the same token endpoint the runner binds the assertion audience to", () => {
    const r = deriveOktaOrganizationIdentity({ orgHost: "acme.okta.com", clientId: "0oaX0000000001" });
    expect(r.ok && r.identity.verifiedTokenEndpoint).toBe("https://acme.okta.com/oauth2/v1/token");
  });

  it("uses the same apex allowlist and identity version", () => {
    expect([...OKTA_APEX_DOMAINS]).toEqual(["okta.com", "oktapreview.com", "okta-emea.com"]);
    expect(OKTA_IDENTITY_VERSION).toBe(1);
  });
});

describe("fingerprint properties", () => {
  it("organizationFingerprint EXCLUDES clientId; serviceAppFingerprint includes it", () => {
    const a = deriveOktaOrganizationIdentity({ orgHost: "acme.okta.com", clientId: "0oaFIRST00000001" });
    const b = deriveOktaOrganizationIdentity({ orgHost: "acme.okta.com", clientId: "0oaSECOND0000002" });
    expect(a.ok && b.ok).toBe(true);
    if (!a.ok || !b.ok) return;
    // Recreating the service app is credential replacement, not a new organization.
    expect(a.identity.organizationFingerprint).toBe(b.identity.organizationFingerprint);
    expect(a.identity.serviceAppFingerprint).not.toBe(b.identity.serviceAppFingerprint);
  });

  it("is stable across every accepted spelling of one host", () => {
    const fps = new Set(["acme.okta.com", "https://acme.okta.com", "https://acme.okta.com/", "ACME.OKTA.COM", "  Acme.Okta.Com/  "]
      .map((h) => { const r = deriveOktaOrganizationIdentity({ orgHost: h, clientId: "0oaX0000000001" }); return r.ok ? r.identity.organizationFingerprint : `REJECTED:${h}`; }));
    expect(fps.size).toBe(1);
  });

  it("differs per host and never collides across a fixture set", () => {
    const hosts: string[] = [];
    for (const apex of OKTA_APEX_DOMAINS) for (let i = 0; i < 30; i++) hosts.push(`org-${i}.${apex}`);
    const org = new Set(hosts.map((h) => { const r = deriveOktaOrganizationIdentity({ orgHost: h, clientId: "0oaX0000000001" }); return r.ok ? r.identity.organizationFingerprint : h; }));
    expect(org.size).toBe(hosts.length);
  });

  it("rejects a malformed client id", () => {
    for (const bad of ["", "has space", "a".repeat(257), null, 42]) {
      expect(deriveOktaOrganizationIdentity({ orgHost: "acme.okta.com", clientId: bad })).toEqual({ ok: false, reason: "client_id_invalid" });
    }
  });
});

describe("host canonicalization matches the runner's rules", () => {
  const accepted = ["acme.okta.com", "acme.okta-emea.com", "acme.oktapreview.com", "https://acme.okta.com", "https://acme.okta.com/", "  ACME.OKTA.COM  ", "trial-5294016.okta.com"];
  const rejected: readonly (readonly [string, string])[] = [
    ["http://acme.okta.com", "not_https"],
    ["user:pass@acme.okta.com", "has_credentials"],   // credentials checked BEFORE the bare-scheme rule
    ["javascript:alert(1)", "has_scheme"],
    ["acme.okta.com:8443", "has_port"],
    ["acme.okta.com/api", "has_path_or_query"],
    ["acme.okta.com?x=1", "has_path_or_query"],
    ["169.254.169.254", "ip_literal"],
    ["[::1]", "ip_literal"],
    ["localhost", "localhost_or_internal"],
    ["okta.internal", "localhost_or_internal"],
    ["okta.com", "apex_only"],
    ["a.b.okta.com", "bad_label"],                    // the org part must be exactly ONE label
    ["acme.notokta.com", "not_okta_apex"],
    ["acme.okta.com.evil.com", "not_okta_apex"],
    ["acme.0kta.com", "not_okta_apex"],
    ["acme.xn--okta-nsa.com", "not_okta_apex"],
    ["id.acme.com", "not_okta_apex"],                 // custom/vanity domains unsupported in v1
    ["acme .okta.com", "has_whitespace"],
  ];

  it.each(accepted)("accepts %s", (h) => expect(canonicalizeOktaOrgHost(h).ok).toBe(true));
  it.each(rejected)("rejects %s → %s", (h, reason) => expect(canonicalizeOktaOrgHost(h)).toEqual({ ok: false, reason }));
});
