#!/usr/bin/env bash
#
# gen-types-local.sh — regenerate src/lib/database.types.ts from the migrations,
# entirely LOCAL. Hosted-proof by construction: like test-rls.sh it spins up its
# OWN throwaway postgres:16 container, applies supabase/migrations/*.sql, then runs
# `supabase gen types typescript --db-url <local>` against that container only.
#
# It NEVER uses --linked / --project-id, never `supabase link` / `db push`, never
# reads a project ref, and reads no secrets. The only DB URL is its own local container.
#
# Requires: docker + the supabase CLI. Usage: bash scripts/gen-types-local.sh
set -euo pipefail

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
IMAGE="${POSTGRES_IMAGE:-postgres:16-alpine}"
PORT=55444
OUT="$REPO/src/lib/database.types.ts"

# Refuse any attempt to point this at something remote.
for arg in "$@"; do
  case "$arg" in
    --linked|--project-id|*://*|*supabase.co*|*supabase.in*|*.supabase.*)
      echo "REFUSED: local-only. This script never targets a hosted/linked project." >&2; exit 2 ;;
    *) echo "unknown arg: $arg"; exit 2 ;;
  esac
done

command -v docker   >/dev/null 2>&1 || { echo "ERROR: docker is required"; exit 1; }
command -v supabase >/dev/null 2>&1 || { echo "ERROR: supabase CLI is required"; exit 1; }

C="idc_gen_types_$$"
cleanup() { docker rm -f "$C" >/dev/null 2>&1 || true; }
trap cleanup EXIT

echo "==> starting $IMAGE ($C) on 127.0.0.1:${PORT}"
docker run -d --name "$C" -e POSTGRES_PASSWORD=postgres -p "127.0.0.1:${PORT}:5432" "$IMAGE" >/dev/null

ok=0
for _ in $(seq 1 60); do
  if docker exec "$C" psql -U postgres -tAc 'select 1' >/dev/null 2>&1; then
    ok=$((ok + 1)); [ "$ok" -ge 3 ] && break
  else ok=0; fi
  sleep 1
done
[ "$ok" -ge 3 ] || { echo "ERROR: postgres did not become ready"; exit 1; }

echo "==> installing Supabase-style auth shim + roles"
docker exec -i "$C" psql -U postgres -d postgres -v ON_ERROR_STOP=1 -q <<'SQL'
create schema if not exists auth;
create table if not exists auth.users (id uuid primary key, email text);
create or replace function auth.uid() returns uuid language sql stable as $$
  select coalesce(
    nullif(current_setting('request.jwt.claim.sub', true), ''),
    nullif(current_setting('request.jwt.claims', true), '')::jsonb ->> 'sub'
  )::uuid;
$$;
do $$ begin
  if not exists (select from pg_roles where rolname='anon')          then create role anon nologin; end if;
  if not exists (select from pg_roles where rolname='authenticated') then create role authenticated nologin; end if;
  if not exists (select from pg_roles where rolname='service_role')  then create role service_role nologin bypassrls; end if;
end $$;
SQL

shopt -s nullglob
for m in "$REPO"/supabase/migrations/*.sql; do
  echo "==> migration $(basename "$m")"
  docker exec -i "$C" psql -U postgres -d postgres -v ON_ERROR_STOP=1 -q < "$m"
done

echo "==> generating types (public schema) → src/lib/database.types.ts"
{
  echo "// AUTO-GENERATED by scripts/gen-types-local.sh from supabase/migrations/*.sql."
  echo "// Do NOT edit by hand. Regenerate locally (never against hosted Supabase)."
  echo ""
  supabase gen types typescript --db-url "postgresql://postgres:postgres@127.0.0.1:${PORT}/postgres" --schema public
} > "$OUT"

echo "==> wrote $OUT ($(wc -l < "$OUT" | tr -d ' ') lines)"
